### ISSUE TITLE
有点小问题

### ISSUE THREAD

**Issue by onecvly** [USS-Shenzhou/MadParticle#10]
1.TNT的爆炸粒子在接管粒子计算的选项为： 仅原版或者原版及其他Mod     时会被吞掉
![媒体播放器 2024_2_8 16_23_57](https://github.com/USS-Shenzhou/MadParticle/assets/102892415/632f7ee7-f20f-4c00-9b7f-e4a12c2c4efb)
正常的：
![媒体播放器 2024_2_8 16_24_40](https://github.com/USS-Shenzhou/MadParticle/assets/102892415/a0429097-5d5c-4789-8eaf-d8cba6f0c431)

2.击败生物冒出的粒子应该一直白的，但是有时候就突然变黑了，然后又很快变回去了（就像闪了一下）
![媒体播放器 2024_2_8 16_29_17](https://github.com/USS-Shenzhou/MadParticle/assets/102892415/a81df188-5781-41de-9714-deb2e66a0083)
正常的：
![媒体播放器 2024_2_8 16_33_30](https://github.com/USS-Shenzhou/MadParticle/assets/102892415/1e971cc5-faa1-47c5-a6f0-f17fd0c839f9)

我不太懂代码....所以我只能提供这些信息了

**Comment by USS-Shenzhou** [comment]
1. 已修复
2. 未能复现，暂时留着

**Comment by onecvly** [comment]
在移动中尝试一下
