### ISSUE TITLE
大佬求解,不太懂Draw-call的优化原理

### ISSUE THREAD

**Issue by Jun-Craft** [USS-Shenzhou/MadParticle#8]
![image](https://github.com/USS-Shenzhou/MadParticle/assets/121743682/e1f9ab90-08ee-4508-9985-10432d547170)
请问这里的render是异步吗，没看懂怎么优化Draw-call

这个继承的是MC的粒子 应该是由主线程执行的？

**Comment by USS-Shenzhou** [comment]
`MadParticleRenderTypes`中的枚举值均是传统渲染方式。实例化渲染的主要内容在[InstancedRenderManager](https://github.com/USS-Shenzhou/MadParticle/blob/instanced-render-test/src/main/java/cn/ussshenzhou/madparticle/particle/InstancedRenderManager.java)。

另外有https://learnopengl-cn.github.io/04%20Advanced%20OpenGL/10%20Instancing/ 供参考
